
package br.edu.utfpr.views;

import java.beans.PropertyVetoException;
import javax.swing.JFrame;


public class FrmPrincipal extends javax.swing.JFrame {


    public FrmPrincipal() {
        initComponents();
        super.setTitle("Dublagem de Filmes");
        super.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDublador = new javax.swing.JMenuItem();
        mnEstudio = new javax.swing.JMenuItem();
        mnLocacao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        mnDublador.setText("Dublador");
        mnDublador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDubladorActionPerformed(evt);
            }
        });
        jMenu1.add(mnDublador);

        mnEstudio.setText("Estudio");
        mnEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEstudioActionPerformed(evt);
            }
        });
        jMenu1.add(mnEstudio);

        mnLocacao.setText("Filme");
        mnLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLocacaoActionPerformed(evt);
            }
        });
        jMenu1.add(mnLocacao);
        jMenu1.add(jSeparator1);

        mnSair.setText("Sair");
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnDubladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDubladorActionPerformed
     
        FrmDubladorPesquisa frmDubladorPesquisa = new FrmDubladorPesquisa();
        desktop.add(frmDubladorPesquisa);
        frmDubladorPesquisa.setVisible(true);
        try {
            frmDubladorPesquisa.setMaximum(true);
        }catch (PropertyVetoException ex){
            ex.printStackTrace();                    
        }
        
    }//GEN-LAST:event_mnDubladorActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        FrmSobre frmSobre = new FrmSobre(this, true);
        frmSobre.setLocationRelativeTo(null);
        frmSobre.setVisible(true);
        frmSobre.focus();
    }//GEN-LAST:event_menuSobreMouseClicked

    private void mnEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEstudioActionPerformed
        FrmEstudioPesquisa frmEstudioPesquisa = new FrmEstudioPesquisa();
        desktop.add(frmEstudioPesquisa);
        frmEstudioPesquisa.setVisible(true);
        try {
            frmEstudioPesquisa.setMaximum(true);
        }catch (PropertyVetoException ex){
            ex.printStackTrace();                    
        }

    }//GEN-LAST:event_mnEstudioActionPerformed

    private void mnLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLocacaoActionPerformed
        FrmFilmePesquisa frmFilmePesquisa = new FrmFilmePesquisa();
        desktop.add(frmFilmePesquisa);
        frmFilmePesquisa.setVisible(true);
        try {
            frmFilmePesquisa.setMaximum(true);
        }catch (PropertyVetoException ex){
            ex.printStackTrace();                    
        }
    }//GEN-LAST:event_mnLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenuItem mnDublador;
    private javax.swing.JMenuItem mnEstudio;
    private javax.swing.JMenuItem mnLocacao;
    private javax.swing.JMenuItem mnSair;
    // End of variables declaration//GEN-END:variables
}
